# Generated by Django 3.0.8 on 2020-10-26 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201026_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Product_Img', models.ImageField(upload_to='images/')),
                ('Price', models.IntegerField()),
                ('categories', models.CharField(default='', max_length=64)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 26, 23, 9, 45, 14901))),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
