# Generated by Django 3.0.8 on 2020-10-28 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201028_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 15, 31, 5, 575331)),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'KIDS')], default='', max_length=64),
        ),
    ]
