# Generated by Django 3.0.8 on 2020-11-06 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20201104_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categort_type',
            field=models.CharField(choices=[('ACCESSORIES', 'Accessories'), ('CLOTHING', 'Clothing'), ('BAGS', 'Bags'), ('SHOES', 'Shoes')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.CharField(choices=[('DRESSES', 'Dresses'), ('TROUSERS', 'Trousers'), ('SWEATERS', 'Sweaters'), ('BLAZERS', 'Blazers'), ('ROMPERS', 'Rompers'), ('T-SHIRTS', 'T-shirts'), ('TOPS', 'Tops'), ('BOOTS', 'Boots'), ('HEALS', 'Heals'), ('SNEAKERS', 'Sneaks')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 11, 6, 42, 832257)),
        ),
    ]
