# Generated by Django 3.0.8 on 2020-11-06 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20201106_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 11, 10, 7, 221982)),
        ),
    ]
